# Generated by Django 5.0.4 on 2024-04-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('palette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(blank=True, max_length=7, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'palette',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='colors',
                        to='palette.palettemodel',
                    ),
                ),
            ],
        ),
    ]
