# Generated by Django 5.0.4 on 2024-04-08 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user_user',
        ),
    ]
