# Generated by Django 5.0.4 on 2024-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
