# Generated by Django 5.0.4 on 2024-04-08 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_usermodel_email_alter_usermodel_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
    ]
